name: Build and Package

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  package-windows:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: Windows-2022
    steps:
      - name: Export Environment Variables
        run: |
          $short_sha=("${{ github.sha }}").substring(0, 7)
          $conanfile_path=$GITHUB_WORKSPACE+"BuildSystem/conanfile.txt"
          Add-Content -Path $env:GITHUB_ENV -Value "GITHUB_SHORT_SHA=$short_sha"
          Add-Content -Path $env:GITHUB_ENV -Value "CONANFILE_PATH=$conanfile_path"
          
        shell: pwsh

      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
          fetch-depth: 1
          lfs: recursive

      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.1

      - name: Get Cmake
        uses: lukka/get-cmake@v3.24.3

      - name: Cache Conan
        id: cache-conan
        uses: actions/cache@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ matrix.configuration }}-conan-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.configuration }}-conan-

      - name: Cache Sharpmake
        id: cache-sharpmake
        uses: actions/cache@v3
        with:
          path: ThirdParty/Sharpmake/tmp
          key: ${{ runner.os }}-${{ matrix.configuration }}-sharpmake-${{ hashFiles(format("{0}{1}", github.workspace, '/ThirdParty/Sharpmake/*.cs')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.configuration }}-sharpmake-

      - name: Cache Generated
        id: cache-generated
        uses: actions/cache@v3
        with:
          path: generated/
          key: ${{ runner.os }}-${{ matrix.configuration }}-generated-${{ hashFiles(format("{0}{1}", github.workspace, '/**/*.ixx'), format("{0}{1}"(github.workspace, '/**/*.cpp') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.configuration }}-generated-

      - name: Run Sharpmake.ps1
        run: ./Tools/Powershell/Sharpmake.ps1
        shell: pwsh
          
      - name: Get msbuild 17
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 17

      - name: Build app for ${{ matrix.configuration }}
        run: msbuild generated\lateralus_vs2022_win64.sln -t:build -property:Configuration=${{ matrix.configuration }}
