name: Build and Package

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  package-windows:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: Windows-2019
    steps:
      - name: Export Environment Variables
        run: |
          $short_sha=("${{ github.sha }}").substring(0, 7)
          Add-Content -Path $env:GITHUB_ENV -Value "GITHUB_SHORT_SHA=$short_sha"
        shell: pwsh
        
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
          fetch-depth: 1
          lfs: recursive
          
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.1

      - name: Get Cmake
        uses: lukka/get-cmake@v3.24.3
          
      - name: Get msbuild 16
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 16
        
      - name: Get msbuild 17
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 17
          
      - name: Run Sharpmake.ps1
        run: ./Tools/Powershell/Sharpmake.ps1
        shell: pwsh

      - name: Build app for ${{ matrix.configuration }}
        run: msbuild generated\lateralus_vs2022_win64.sln -t:rebuild -verbosity:diag -property:Configuration=${{ matrix.configuration }}
